### PR TITLE
only minify HTML content, fixes #24

### LINKED ISSUE #24: JSON breaks when HTML minification is turned on.
After enabling HTML minifications, JSON response breaks its structure. "content-type" in response header was application/json and the response data had some HTML content. I think the module also minified that HTML content too. It was generated using Magento's _toHtml() function.

### PR DESCRIPTION
**Pull request by sprankhub**

### CODE REVIEW

**Comment by sprankhub** [comment]
Unfortunately, Magento sends a `text/html` content type header for JSON responses as well. Hence, we have to check for JSON responses manually (see b48756a) :-/

**Comment by sprankhub** [comment]
@fooman could you please check and merge? Seems to work, see #24.

**Comment by omolto** [comment]
Yes, it works now! ;)

**Comment by fooman** [comment]
Thanks @sprankhub

**Pull request merged**
