### PR TITLE
fixed HTML minify issue with full page caching extensions, fixes #26

### LINKED ISSUE #26: HTML minify conflicts with Varnish caching
If i enable HTML minify, the whole header section disappears from all our sites (using different themes).

Example:
https://www.fyr-selv.dk/taendbreve.html

header-dissapears

It seems to be a conflict with Varnish (via Turpentine https://github.com/nexcess/magento-turpentine), as it doesn't occur in the checkout flow, which isn't being cached. Also if i bypass Varnish, it displays correctly.

The whole header section isn't present in the outputted html.
The header section get's cached seperately via ESI hole-punching to display the dynamic contents properly.

### PR DESCRIPTION
**Pull request by sprankhub**

### CODE REVIEW

**Comment by sprankhub** [comment]
Could you please merge this @fooman?

**Comment by fooman** [comment]
Hmm looks like this now has a merge conflict. Would you mind taking a look?

**Comment by sprankhub** [comment]
Should be fixed and ready to merge @fooman :)

**Comment by fooman** [comment]
Good stuff - I'll give it a bit of time in master and then provided nothing else comes up tag a new release.

**Comment by sprankhub** [comment]
Thanks Kristof!

**Pull request merged**
